"""
PR Review Agent — FastAPI Backend
"""

import asyncio
import json
import os
from pathlib import Path

import httpx
from dotenv import load_dotenv

load_dotenv()  # reads .env if present
from fastapi import FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, HTMLResponse, PlainTextResponse, StreamingResponse
from pydantic import BaseModel

from agent.graph import stream_review
from agent.llm_factory import PROVIDER_MODELS

app = FastAPI(title="PR Review Agent")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

STATIC_DIR = Path(__file__).parent / "static"
PROMPT_TEMPLATE = Path(__file__).parent / "prompt-template.txt"


# ── Serve UI ───────────────────────────────────────────────────────────────

@app.get("/")
async def index():
    return FileResponse(STATIC_DIR / "index.html")


# ── Health ─────────────────────────────────────────────────────────────────

@app.get("/api/health")
async def health():
    return {"status": "ok"}


# ── LLM providers metadata (used by frontend to build dropdowns) ───────────

@app.get("/api/providers")
async def providers():
    return PROVIDER_MODELS


# ── Prompt template ────────────────────────────────────────────────────────

@app.get("/api/prompt-template")
async def get_prompt_template():
    """Return the contents of prompt-template.txt."""
    if not PROMPT_TEMPLATE.exists():
        raise HTTPException(404, "prompt-template.txt not found.")
    return PlainTextResponse(PROMPT_TEMPLATE.read_text(encoding="utf-8"))


@app.get("/api/build-template")
async def build_template():
    """Generate and return a standalone pr-review.html with the prompt embedded."""
    if not PROMPT_TEMPLATE.exists():
        raise HTTPException(404, "prompt-template.txt not found.")

    prompt_text = PROMPT_TEMPLATE.read_text(encoding="utf-8").strip()
    prompt_js = (
        prompt_text
        .replace("\\", "\\\\")
        .replace("`", "\\`")
        .replace("${", "\\${")
    )

    html = _STANDALONE_TEMPLATE.replace("__PROMPT__", prompt_js)
    return HTMLResponse(
        content=html,
        headers={"Content-Disposition": 'attachment; filename="pr-review.html"'},
    )


_STANDALONE_TEMPLATE = r"""<!DOCTYPE html>
<!--
  PR Review Standalone Template
  Generated by PR Review Agent — /api/build-template
  Edit prompt-template.txt on the server and re-download to update.

  HOW TO USE
    1. Enter GitHub token (optional), repo, PR number and click Fetch
       — OR paste a diff manually
    2. Click "Build Review Template"
    3. Click "Copy filled prompt" → paste into Claude / ChatGPT / any AI
-->
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>PR Review Template</title>
<style>
:root{
  --bg:#0d1117;--sur:#161b22;--sur2:#21262d;--bdr:#30363d;
  --txt:#e6edf3;--mut:#8b949e;--acc:#58a6ff;
  --grn:#3fb950;--grn-bg:rgba(63,185,80,.15);
  --red:#f85149;--red-bg:rgba(248,81,73,.15);
  --blu-bg:rgba(88,166,255,.10);--amb:#d29922;
  --r:6px;--mono:"SFMono-Regular",Consolas,"Liberation Mono",Menlo,monospace;
}
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
html,body{height:100%}
body{background:var(--bg);color:var(--txt);
  font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif;
  font-size:14px;display:flex;flex-direction:column;height:100vh;overflow:hidden}
header{background:var(--sur);border-bottom:1px solid var(--bdr);
  padding:0 20px;height:52px;display:flex;align-items:center;
  justify-content:space-between;flex-shrink:0}
header h1{font-size:16px;font-weight:600;display:flex;align-items:center;gap:8px}
header h1 svg{color:var(--acc)}
#sw{display:flex;align-items:center;gap:6px;font-size:12px;color:var(--mut)}
#sd{width:8px;height:8px;border-radius:50%;background:var(--grn)}
#sd.busy{background:var(--amb);animation:blink 1s ease-in-out infinite}
@keyframes blink{0%,100%{opacity:1}50%{opacity:.3}}
main{display:flex;flex:1;overflow:hidden}
.pnl{display:flex;flex-direction:column;border-right:1px solid var(--bdr);overflow:hidden}
.pnl:last-child{border-right:none}
.ph{padding:9px 14px;font-size:11px;font-weight:600;text-transform:uppercase;
  letter-spacing:.06em;color:var(--mut);border-bottom:1px solid var(--bdr);
  background:var(--sur);flex-shrink:0}
.pb{flex:1;overflow-y:auto;padding:14px}
.pb::-webkit-scrollbar{width:6px}
.pb::-webkit-scrollbar-thumb{background:var(--bdr);border-radius:3px}
#pL{width:270px;min-width:270px}
.fg{margin-bottom:12px}
label{display:block;font-size:12px;font-weight:500;color:var(--mut);margin-bottom:4px}
input,textarea{width:100%;background:var(--sur2);border:1px solid var(--bdr);
  border-radius:var(--r);color:var(--txt);font-size:13px;padding:7px 10px;
  outline:none;font-family:inherit;transition:border-color .15s}
input:focus,textarea:focus{border-color:var(--acc)}
textarea{resize:vertical;font-family:var(--mono);font-size:12px}
hr.dv{border:none;border-top:1px solid var(--bdr);margin:14px 0}
.btn{display:inline-flex;align-items:center;justify-content:center;gap:6px;
  padding:7px 14px;border-radius:var(--r);font-size:13px;font-weight:500;
  cursor:pointer;border:1px solid transparent;width:100%;
  transition:opacity .15s,background .15s}
.btn:disabled{opacity:.4;cursor:not-allowed}
.btn-o{background:var(--sur2);border-color:var(--bdr);color:var(--txt)}
.btn-o:hover:not(:disabled){background:var(--bdr)}
.btn-f{background:var(--acc);color:#0d1117;font-weight:600}
.btn-f:hover:not(:disabled){opacity:.85}
.sp{width:13px;height:13px;border:2px solid currentColor;border-top-color:transparent;
  border-radius:50%;animation:spin .6s linear infinite;display:none}
.btn.loading .sp{display:block}.btn.loading .lbl{display:none}
@keyframes spin{to{transform:rotate(360deg)}}
.eb{display:none;background:var(--red-bg);border:1px solid var(--red);
  border-radius:var(--r);color:var(--red);padding:7px 10px;
  font-size:12px;margin-bottom:10px;line-height:1.5}
.eb.on{display:block}
#pD{flex:1}
#meta{display:none;flex-wrap:wrap;gap:8px;padding:8px 14px;
  border-bottom:1px solid var(--bdr);background:var(--sur);flex-shrink:0}
#meta.on{display:flex}
#ptit{font-weight:600;font-size:13px;width:100%}
.badge{display:inline-flex;align-items:center;gap:4px;
  font-size:11px;padding:2px 8px;border-radius:20px;font-weight:500}
.bm{background:var(--sur2);color:var(--mut);border:1px solid var(--bdr)}
.bg2{background:var(--grn-bg);color:var(--grn)}
.br2{background:var(--red-bg);color:var(--red)}
#dscr{flex:1;overflow-y:auto}
#demp{display:flex;flex-direction:column;align-items:center;justify-content:center;
  height:100%;color:var(--mut);gap:8px;font-size:13px}
#demp svg{opacity:.25}
.dtbl{width:100%;border-collapse:collapse;font-family:var(--mono);font-size:12px;line-height:1.5}
.dtbl td{padding:0 8px;white-space:pre}
.dln{color:var(--mut);text-align:right;user-select:none;min-width:40px;
  border-right:1px solid var(--bdr);padding-right:10px !important}
.dco{width:100%}
tr.da{background:var(--grn-bg);color:var(--grn)}
tr.dd{background:var(--red-bg);color:var(--red)}
tr.dh{background:var(--blu-bg);color:var(--acc);font-size:11px}
tr.df{background:var(--sur2);color:var(--mut);font-weight:700}
tr.dn td{color:var(--txt)}
#pT{width:420px;min-width:420px}
#tbar{display:flex;align-items:center;gap:8px;padding:6px 14px;
  border-bottom:1px solid var(--bdr);background:var(--sur);flex-shrink:0}
#thnt{font-size:11px;color:var(--mut);margin-right:auto}
.ib{background:none;border:1px solid var(--bdr);border-radius:var(--r);
  color:var(--mut);cursor:pointer;padding:4px 10px;font-size:11px;
  display:inline-flex;align-items:center;gap:4px;
  transition:color .15s,border-color .15s}
.ib:hover{color:var(--txt);border-color:var(--mut)}
.ib:disabled{opacity:.35;cursor:not-allowed}
#tinn{flex:1;overflow-y:auto;display:flex;flex-direction:column}
#tsec{border-bottom:1px solid var(--bdr);flex-shrink:0}
#tlbl{font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:.05em;
  color:var(--mut);padding:8px 14px 4px}
#tta{width:100%;background:transparent;border:none;color:var(--txt);
  font-family:var(--mono);font-size:12px;line-height:1.6;
  padding:8px 14px 12px;resize:none;outline:none;min-height:220px}
#pvsec{flex:1;overflow-y:auto}
#pvlbl{font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:.05em;
  color:var(--mut);padding:10px 14px 4px;position:sticky;top:0;
  background:var(--bg);z-index:1}
#pvout{font-family:var(--mono);font-size:12px;line-height:1.6;color:var(--mut);
  padding:4px 14px 20px;white-space:pre-wrap;word-break:break-word}
.hm{color:var(--acc)}.hd{color:var(--txt)}.he{color:var(--bdr);font-style:italic}
@media(max-width:960px){
  body{overflow:auto}main{flex-direction:column;overflow:visible}
  .pnl{width:100% !important;min-width:0 !important;
    border-right:none;border-bottom:1px solid var(--bdr)}
  #pD,#pT{min-height:360px}
}
</style>
</head>
<body>
<header>
  <h1>
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
      <circle cx="18" cy="18" r="3"/><circle cx="6" cy="6" r="3"/>
      <path d="M6 9v1a3 3 0 0 0 3 3h6a3 3 0 0 1 3 3v1"/>
    </svg>
    PR Review Template
  </h1>
  <div id="sw"><div id="sd"></div><span id="stxt">Ready</span></div>
</header>
<main>
  <!-- LEFT -->
  <section class="pnl" id="pL">
    <div class="ph">Load PR</div>
    <div class="pb">
      <div id="err" class="eb"></div>
      <div class="fg">
        <label>GitHub Token <span style="font-weight:400;font-size:11px">— optional</span></label>
        <input id="tok" type="password" placeholder="ghp_..." autocomplete="off"/>
      </div>
      <div class="fg">
        <label>Repository</label>
        <input id="rpo" type="text" placeholder="owner/repo"/>
      </div>
      <div class="fg">
        <label>PR Number</label>
        <input id="prn" type="number" placeholder="42" min="1"/>
      </div>
      <button class="btn btn-o" id="bfetch">
        <span class="sp"></span><span class="lbl">Fetch PR from GitHub</span>
      </button>
      <hr class="dv"/>
      <div class="fg">
        <label>— or paste a diff manually —</label>
        <textarea id="idiff" rows="7" placeholder="Paste unified diff here..."></textarea>
      </div>
      <div class="fg">
        <label>PR Title <span style="font-weight:400">(optional)</span></label>
        <input id="itit" type="text" placeholder="e.g. Fix: null pointer on login"/>
      </div>
      <div class="fg">
        <label>PR Description <span style="font-weight:400">(optional)</span></label>
        <textarea id="idesc" rows="3" placeholder="What does this PR do?"></textarea>
      </div>
      <button class="btn btn-f" id="bbuild" disabled>Build Review Template →</button>
    </div>
  </section>
  <!-- CENTER: Diff viewer -->
  <section class="pnl" id="pD">
    <div class="ph">Diff Viewer</div>
    <div id="meta">
      <span id="ptit"></span>
      <span id="ba" class="badge bm"></span>
      <span id="bb" class="badge bm"></span>
      <span id="bf" class="badge bm"></span>
      <span id="bplus" class="badge bg2"></span>
      <span id="bminus" class="badge br2"></span>
    </div>
    <div id="dscr">
      <div id="demp">
        <svg width="44" height="44" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4">
          <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
          <polyline points="14 2 14 8 20 8"/>
          <line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/>
        </svg>
        <p>Fetch a PR or paste a diff</p>
      </div>
    </div>
  </section>
  <!-- RIGHT: Template -->
  <section class="pnl" id="pT">
    <div class="ph">Review Template</div>
    <div id="tbar">
      <span id="thnt">Edit the template, then copy the filled result</span>
      <button class="ib" id="bcopy" disabled>
        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <rect x="9" y="9" width="13" height="13" rx="2"/>
          <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/>
        </svg>
        Copy filled prompt
      </button>
    </div>
    <div id="tinn">
      <div id="tsec">
        <div id="tlbl">Prompt Template — edit freely</div>
        <textarea id="tta" spellcheck="false"></textarea>
      </div>
      <div id="pvsec">
        <div id="pvlbl">Filled Preview</div>
        <div id="pvout"><span class="he">Load a diff and click "Build Review Template" to see the filled prompt here.</span></div>
      </div>
    </div>
  </section>
</main>
<script>
const DEFAULT_PROMPT = `__PROMPT__`;
let curDiff = '', filled = '';
const $ = id => document.getElementById(id);
const tok=$('tok'),rpo=$('rpo'),prn=$('prn'),idiff=$('idiff'),itit=$('itit'),idesc=$('idesc'),
      bfetch=$('bfetch'),bbuild=$('bbuild'),bcopy=$('bcopy'),err=$('err'),
      tta=$('tta'),pvout=$('pvout'),thnt=$('thnt'),
      sd=$('sd'),stxt=$('stxt'),meta=$('meta'),dscr=$('dscr'),demp=$('demp');
tta.value = DEFAULT_PROMPT;
['rpo','prn','itit','idesc','idiff'].forEach(id => {
  const el=$(id), v=localStorage.getItem('pr_'+id);
  if(v) el.value=v;
  el.addEventListener('input', () => localStorage.setItem('pr_'+id, el.value));
});
const setStatus=(t,b=false)=>{ stxt.textContent=t; sd.className=b?'busy':''; };
const showErr=m=>{ err.textContent=m; err.classList.add('on'); };
const clearErr=()=>err.classList.remove('on');
const setLoad=(btn,v)=>{ btn.disabled=v; v?btn.classList.add('loading'):btn.classList.remove('loading'); };
const updBuild=()=>{ bbuild.disabled=!curDiff.trim(); };
const esc=s=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
bfetch.addEventListener('click', async () => {
  clearErr();
  const t=tok.value.trim(), r=rpo.value.trim(), n=parseInt(prn.value);
  if(!r){ showErr('Repository required (e.g. owner/repo).'); return; }
  if(!n||n<1){ showErr('Enter a valid PR number.'); return; }
  setLoad(bfetch,true); setStatus('Fetching…',true);
  const h={'User-Agent':'pr-review-template'};
  if(t) h['Authorization']='Bearer '+t;
  try {
    const mr=await fetch(`https://api.github.com/repos/${r}/pulls/${n}`,{headers:h});
    if(mr.status===401) throw new Error('Invalid GitHub token.');
    if(mr.status===403) throw new Error('Rate limit hit, or token needs "repo" scope.');
    if(mr.status===404) throw new Error(`PR #${n} not found in "${r}".`);
    if(!mr.ok) throw new Error('GitHub API error: HTTP '+mr.status);
    const m=await mr.json();
    const dr=await fetch(`https://api.github.com/repos/${r}/pulls/${n}`,
      {headers:{...h,Accept:'application/vnd.github.v3.diff'}});
    if(!dr.ok) throw new Error('Could not fetch diff: HTTP '+dr.status);
    const d=await dr.text();
    if(d.length>150000) throw new Error('Diff too large (>150 KB). Paste a portion manually.');
    $('ptit').textContent=m.title; $('ba').textContent='@'+(m.user?.login||'');
    $('bb').textContent=(m.base?.ref)+' ← '+(m.head?.ref);
    $('bf').textContent=m.changed_files+' file'+(m.changed_files!==1?'s':'');
    $('bplus').textContent='+'+m.additions; $('bminus').textContent='-'+m.deletions;
    meta.classList.add('on');
    itit.value=m.title; localStorage.setItem('pr_itit',m.title);
    curDiff=d; idiff.value=d; localStorage.setItem('pr_idiff',d);
    renderDiff(d); updBuild(); setStatus('Loaded PR #'+n,false);
  } catch(e){ showErr(e.message); setStatus('Ready',false); }
  finally{ setLoad(bfetch,false); }
});
idiff.addEventListener('input',()=>{ curDiff=idiff.value; renderDiff(curDiff); updBuild(); });
function renderDiff(text){
  const old=dscr.querySelector('.dtbl'); if(old) old.remove();
  if(!text.trim()){ demp.style.display=''; return; }
  demp.style.display='none';
  const tbl=document.createElement('table'); tbl.className='dtbl';
  let nl=0;
  text.split('\n').forEach(line=>{
    const tr=document.createElement('tr');
    const tn=document.createElement('td'); tn.className='dln';
    const tc=document.createElement('td'); tc.className='dco';
    if(/^(diff --git|index |--- |\+\+\+ |new file|deleted file)/.test(line)){
      tr.className='df'; tn.textContent='';
    } else if(line.startsWith('@@')){
      tr.className='dh'; tn.textContent='…';
      const mm=line.match(/@@ -\d+(?:,\d+)? \+(\d+)/);
      if(mm) nl=parseInt(mm[1])-1;
    } else if(line.startsWith('+')){
      tr.className='da'; tn.textContent=++nl;
    } else if(line.startsWith('-')){
      tr.className='dd'; tn.textContent='';
    } else {
      tr.className='dn'; tn.textContent=++nl;
    }
    tc.textContent=line;
    tr.appendChild(tn); tr.appendChild(tc); tbl.appendChild(tr);
  });
  dscr.appendChild(tbl);
}
function build(){
  const tpl=tta.value;
  const t=itit.value.trim()||'(no title)';
  const d=idesc.value.trim()||'(no description)';
  const df=curDiff.trim()||'(no diff)';
  filled=tpl.replace('{pr_title}',t).replace('{pr_description}',d).replace('{diff}',df);
  pvout.innerHTML=esc(tpl)
    .replace(esc('{pr_title}'),`<span class="hm">${esc(t)}</span>`)
    .replace(esc('{pr_description}'),`<span class="hm">${esc(d)}</span>`)
    .replace(esc('{diff}'),`<span class="hd">${esc(df)}</span>`);
  bcopy.disabled=false;
  thnt.textContent='Ready — copy and paste into Claude, ChatGPT, or any AI';
}
bbuild.addEventListener('click', build);
tta.addEventListener('input',()=>{ if(curDiff) build(); });
bcopy.addEventListener('click', async ()=>{
  if(!filled) return;
  try {
    await navigator.clipboard.writeText(filled);
    const o=bcopy.innerHTML;
    bcopy.innerHTML='<svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="20 6 9 17 4 12"/></svg> Copied!';
    setTimeout(()=>bcopy.innerHTML=o, 1800);
  } catch{}
});
if(idiff.value.trim()){ curDiff=idiff.value; renderDiff(curDiff); updBuild(); }
</script>
</body>
</html>"""


# ── Fetch PR ───────────────────────────────────────────────────────────────

class FetchPRRequest(BaseModel):
    host: str          # "github" | "bitbucket"
    token: str = ""
    repo: str          # "owner/repo"  or  "workspace/repo"
    pr_number: int


@app.post("/api/fetch-pr")
async def fetch_pr(req: FetchPRRequest):
    # Use token from request; fall back to env var
    token = req.token.strip() or os.getenv("GITHUB_TOKEN", "")
    headers = {"User-Agent": "pr-review-agent"}
    if token:
        headers["Authorization"] = f"Bearer {token}"

    async with httpx.AsyncClient(timeout=30) as client:
        if req.host == "github":
            meta_url = f"https://api.github.com/repos/{req.repo}/pulls/{req.pr_number}"
            meta_r = await client.get(meta_url, headers=headers)
            _raise_for_git_error(meta_r, "GitHub", req.pr_number, req.repo)
            m = meta_r.json()

            diff_r = await client.get(
                meta_url,
                headers={**headers, "Accept": "application/vnd.github.v3.diff"},
            )
            diff_r.raise_for_status()
            diff = diff_r.text

            return {
                "diff": _check_diff_size(diff),
                "title": m.get("title", ""),
                "author": m.get("user", {}).get("login", ""),
                "base_branch": m.get("base", {}).get("ref", ""),
                "head_branch": m.get("head", {}).get("ref", ""),
                "additions": m.get("additions", 0),
                "deletions": m.get("deletions", 0),
                "changed_files": m.get("changed_files", 0),
                "body": m.get("body", "") or "",
            }

        elif req.host == "bitbucket":
            parts = req.repo.split("/", 1)
            if len(parts) != 2:
                raise HTTPException(400, "Repo must be 'workspace/repo' for Bitbucket.")
            workspace, repo_slug = parts
            base = "https://api.bitbucket.org/2.0"

            meta_r = await client.get(
                f"{base}/repositories/{workspace}/{repo_slug}/pullrequests/{req.pr_number}",
                headers=headers,
            )
            _raise_for_git_error(meta_r, "Bitbucket", req.pr_number, req.repo)
            m = meta_r.json()

            diff_r = await client.get(
                f"{base}/repositories/{workspace}/{repo_slug}/pullrequests/{req.pr_number}/diff",
                headers={**headers, "Accept": "text/plain"},
            )
            diff_r.raise_for_status()
            diff = diff_r.text

            return {
                "diff": _check_diff_size(diff),
                "title": m.get("title", ""),
                "author": m.get("author", {}).get("display_name", ""),
                "base_branch": m.get("destination", {}).get("branch", {}).get("name", ""),
                "head_branch": m.get("source", {}).get("branch", {}).get("name", ""),
                "additions": 0,
                "deletions": 0,
                "changed_files": 0,
                "body": m.get("description", "") or "",
            }

        else:
            raise HTTPException(400, f"Unknown host: {req.host!r}. Use 'github' or 'bitbucket'.")


def _raise_for_git_error(resp: httpx.Response, host: str, pr_number: int, repo: str):
    if resp.status_code == 401:
        raise HTTPException(401, f"Invalid {host} token.")
    if resp.status_code == 403:
        raise HTTPException(403, f"{host} rate limit hit or token lacks required scope.")
    if resp.status_code == 404:
        raise HTTPException(404, f"PR #{pr_number} not found in '{repo}'.")
    resp.raise_for_status()


def _check_diff_size(diff: str) -> str:
    if len(diff) > 150_000:
        raise HTTPException(413, "Diff too large (>150 KB). Paste a smaller portion manually.")
    return diff


# ── Review (SSE stream) ────────────────────────────────────────────────────

class ReviewRequest(BaseModel):
    llm_provider: str
    api_key: str
    model: str
    diff: str
    pr_title: str = ""
    pr_description: str = ""


ENV_KEYS = {
    "groq":     os.getenv("GROQ_API_KEY", ""),
    "openai":   os.getenv("OPENAI_API_KEY", ""),
    "anthropic":os.getenv("ANTHROPIC_API_KEY", ""),
    "gemini":   os.getenv("GOOGLE_API_KEY", ""),
}

@app.get("/api/env-key")
async def env_key(provider: str):
    """Return whether an env key exists for a provider (value hidden)."""
    key = ENV_KEYS.get(provider.lower(), "")
    return {"has_key": bool(key)}

@app.post("/api/review")
async def review(req: ReviewRequest):
    # Fall back to env key if the user left the field blank
    api_key = req.api_key.strip() or ENV_KEYS.get(req.llm_provider.lower(), "")
    if not api_key:
        raise HTTPException(400, "API key is required.")
    if not req.diff.strip():
        raise HTTPException(400, "Diff is required.")

    async def event_stream():
        try:
            async for chunk in stream_review(
                provider=req.llm_provider,
                api_key=api_key,
                model=req.model,
                diff=req.diff,
                pr_title=req.pr_title,
                pr_description=req.pr_description,
            ):
                if chunk:
                    yield f"data: {json.dumps(chunk)}\n\n"
        except Exception as e:
            yield f"data: {json.dumps({'error': str(e)})}\n\n"
        finally:
            yield "data: [DONE]\n\n"

    return StreamingResponse(
        event_stream(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
        },
    )
